export default {
  colors: {
    error: '#e74c3c',
    neutralL0: '#808080',
    neutralL1: '#bfbfbf',
    neutralL2: '#d9d9d9',
    neutralL3: '#f2f2f2',
    neutralL4: '#fcfcfc',
    otherYellow: '#fdbe32',
    otherYellowL1: '#ffe3a6',
    primary: '#00a877',
    primaryD1: '#006648',
    primaryD2: '#003324',
    primaryL1: '#47A882',
    primaryL2: '#53C8A4',
    secondary: '#1e262a',
    secondaryD1: '#161c20',
    secondaryD2: '#0f1315',
    secondaryD3: '#08090b',
    secondaryL1: '#2e3a40',
    secondaryL2: '#4a5b64',
  },
  family: {
    light: 'Montserrat-Light',
    regular: 'Montserrat-Regular',
    medium: 'Montserrat-Medium',
    bold: 'Montserrat-Bold',
    black: 'Montserrat-Black',

    // light: "sans-serif",
    // regular: "sans-serif",
    // medium: "sans-serif",
    // bold: "sans-serif",
    // black: "sans-serif",
  },
  size: {
    h1: '30px',
    h2: '26px',
    h3: '22px',
    h4: '20px',
    h5: '18px',
    p: '16px',
    label: '14px',
    small: '12px',
    xsmall: '10px',
  },
  lineHeight: {
    h1: '30px',
    h2: '26px',
    h3: '22px',
    h4: '20px',
    h5: '18px',
    p: '16px',
    label: '18px',
    small: '12px',
    xsmall: '10px',
  },
  fonts: {
    bigInfo: {
      fontFamily: 'OpenSans-Bold',
      fontSize: '14px',
      letterSpacing: '0px',
    },
    bigTitle: {
      fontFamily: 'OpenSans-Bold',
      fontSize: '24px',
      letterSpacing: '0px',
    },
    info: {
      fontFamily: 'OpenSans-Regular',
      fontSize: '14px',
      letterSpacing: '-0.7px',
    },
    smallInfo: {
      fontFamily: 'OpenSans-SemiBold',
      fontSize: '12px',
      letterSpacing: '0px',
    },
    label: {
      fontFamily: 'OpenSans-SemiBold',
      fontSize: '10px',
      letterSpacing: '0px',
    },
    text: {
      fontFamily: 'OpenSans-Regular',
      fontSize: '16px',
      letterSpacing: '0px',
    },
    smallText: {
      fontFamily: 'OpenSans-Regular',
      fontSize: '14px',
      letterSpacing: '0px',
    },
    smallTitle: {
      fontFamily: 'OpenSans-Regular',
      fontSize: '14px',
      letterSpacing: '0px',
    },
    title: {
      fontFamily: 'OpenSans-Bold',
      fontSize: '18px',
      letterSpacing: '0px',
    },
    help: {
      fontFamily: 'Open Sans',
      fontSize: '12px',
      letterSpacing: '0px',
    },
    h1: {
      fontFamily: 'OpenSans-Bold',
      fontSize: '32px',
      letterSpacing: '0px',
    },
  },
};
